const styles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      height: '668px',
      width: '400px',
      fontFamily: 'sans-serif',
      backgroundColor: '#fff',
    },
    header: {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      padding: '14px',
      borderBottom: '1px solid #989898',
    },
    backButton: {
      fontSize: '18px',
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      color: '#000',
    },
    title: {
      marginLeft: 'auto',
      marginRight: 'auto',
      fontSize: '14px',
      fontWeight: '400',
    },
    main: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      width: '100%',
      maxWidth: '400px',
      padding: '48px',
    },
    loginTitle: {
      fontSize: '24px',
      fontWeight: 'bold',
      margin: '20px 0',
    },
    label: {
      width: '100%',
      marginBottom: '22px',
      fontSize: '14px',
      fontWeight: 'bold',
      color: '#232323',
    },
    input: {
      width: '100%',
      padding: '8px',
      marginTop: '12px',
      fontSize: '12px',
      borderRadius: '5px',
      border: 'none',
      backgroundColor: '#ECECEC',
      outline: 'none',
    },
    loginButton: {
      width: '100%',
      padding: '11px',
      marginTop: '30px',
      fontSize: '14px',
      fontWeight: 'bold',
      color: '#fff',
      backgroundColor: '#5B3200',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
    },
    signupButton: {
      width: '100%',
      padding: '11px',
      marginTop: '15px',
      fontSize: '14px',
      fontWeight: 'bold',
      color: '#232323',
      backgroundColor: '#ffffe5',
      border: '1.5px solid #E3B05F',
      borderRadius: '5px',
      cursor: 'pointer',
    },
  };
  
  export default styles;
  