// mockLocations.js
export const mockLocations = [
  {
    id: 1,
    nickname: "이름1",
    title: "Q&A 게시물 제목",
    content: "Q&A 게시물 내용",
    type: "실시간",
    imageUrl: "/images/adding_dots.svg",
    likesCount: 45,
    commentCount: 5,
    urgent: false,
    mode: "실시간 Q&A",
    createdAt: "2024-10-29T12:34:56",
    comments: [],
    locations: [
      "37.5665",
      "126.9780",
      "서울특별시 중구 장충동2가"
    ],
  },
  {
    id: 2,
    nickname: "이름2",
    title: "커뮤니티 게시물 제목",
    content: "커뮤니티 게시물 내용",
    type: "실시간",
    imageUrl: "/images/preview.jpeg",
    likesCount: 10,
    commentCount: 2,
    urgent: false,
    mode: "실시간 기록",
    createdAt: "2024-10-29T12:35:56",
    comments: [],
    locations: [
      "37.5700",
      "126.9765",
      "서울특별시 중구 장충동2가"
    ],
  },
  {
    id: 3,
    nickname: "이름3",
    title: "실시간 제보",
    content: "이곳에서 동물을 목격했습니다.",
    type: "실시간",
    imageUrl: "/images/sidebar_my.svg",
    likesCount: 25,
    commentCount: 3,
    urgent: false,
    mode: "실시간 기록",
    createdAt: "2024-10-30T14:20:00",
    comments: [],
    locations: [
      "37.5640",
      "126.9820",
      "서울특별시 중구 장충동2가"
    ],
  },
  {
    id: 4,
    nickname: "이름4",
    title: "우동친 제보",
    content: "새로운 우동친 제보 내용입니다.",
    type: "실시간",
    imageUrl: "/images/currentLocationImage.svg",
    likesCount: 30,
    commentCount: 1,
    urgent: false,
    mode: "실시간 Q&A",
    createdAt: "2024-10-30T15:00:00",
    comments: [],
    locations: [
      "37.5610",
      "126.9900",
      "서울특별시 중구 장충동2가"
    ],
  },
  {
    id: 5,
    nickname: "긴급",
    title: "긴급급",
    content: "아주 긴급급",
    type: "실시간",
    imageUrl: "/images/currentLocationImage.svg",
    likesCount: 34,
    commentCount: 0,
    urgent: true,
    mode: "실시간 Q&A",
    createdAt: "2024-10-30T15:00:00",
    comments: [],
    locations: [
      "37.5600",
      "126.9911",
      "서울특별시 중구 장충동2가"
    ],
  },
  {
    id: 8,
    nickname: "nickname",
    title: "제목",
    content: "내용",
    type: "실시간",
    imageUrl: "/images/currentLocationImage.svg",
    likesCount: 0,
    commentCount: 0,
    urgent: false,
    mode: "실시간 기록",
    createdAt: "2024-11-07T14:38:16.098992",
    comments: [],
    locations: [
      "37.5590",
      "126.9920",
      "서울특별시 중구 장충동2가"
    ],
  },
];

