// src/constants/routeConstants.js
export const ROUTE_PATHS = {
  HOME: "/",
  REPORT: "/report",
  MYUDCHISTORY: "/myudchistory",
  UDCMANUAL: "/udcmanual",
  ABOUT: "/about",
  CONTACT: "/contact",
  NOT_FOUND: "*",
  LOGIN: "/login",
  JOIN: "/join",
  POST_WRITE: "/postwrite",
  PR_WRITE: "/prwrite",
  POST_VIEW: "/postview/:id",
  PR_VIEW: "/prview/:id",
  COMMUNITY: "/community",
  PRBOARD: "/prboard",
  FREEBOARD:"/freeboard",
  EDITPOST:"/edit",
};
